name: docker

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main

    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/} | sed 's/.*\///')"
      id: extract_branch

    - name: build image
      run: docker build -t ghcr.io/minetest-hosting/minetest-docker:${{ steps.extract_branch.outputs.branch }} .

    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push image
      run: docker push ghcr.io/minetest-hosting/minetest-docker:${{ steps.extract_branch.outputs.branch }}
